spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/qk_springcloud?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  zipkin:
    base-url: http://47.96.155.220:9411/ # zipkin服务器的地址
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1.0  # 设置抽样采集为100%，默认为0.1，即10%



server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


logging:
  level:
    org.springframework.cloud.openfeign: debug

